### ISSUE TITLE
Acer spin 713 incorrect temperature reading

### ISSUE THREAD

**Issue by vladann93** [death7654/Chrultrabook-Tools#80]
I installed all the coolstar drivers, and by default it blasts the fans at full speed always. Core temp is reading the cpu temp correctly. Chrultrabook-Tools works to fix the fan curve but its reading the cpu temp incorrectly. 

When the cpu reaches 90c and starts throttling, the fans are still off with Chrultrabook-Tools, it then slowly over the course of like 2-3min picks up the fan speed. The temperature its reading is like 40-50c under prime95, and like 35c when idle.

I tried multiple versions. 3.0 and older all the same..

Could you help me fix this, thanks!

**Comment by death7654** [comment]
There is an issue with ectools where when you cold start a chromebook, the BIOS and the OS fight each other over control of the fans. The best and only current solution is to heat up the chromebook, and do a full restart where the OS can fully take over control of the chromebooks fans allowing the chrultrabook-tools app to control you fans. 

Please send a screenshot of the chrultrabook tools app, and prime95 while your chromebook is currently under load.

**Comment by vladann93** [comment]
Nah, something is wrong with that specific device, I also saw multiple comments online for that model where the fans wont stop even on chromeos... I have two other devices and they act completley normal, an acer i5 8250u and a lenovo r5 3500c.

Idk, i adjusted the fan curve to be more agressive, and it kinda does it now.. Not perfect but a lot less annoying.

But it would be nice if Chrultrabook-Tools could read the same temperature sensor as Core temp

**Comment by zyy574** [comment]
It looks like that you read temperatures by ectool and calculate the average of all the temperature as CPU temp to control the fan. However, in most devices, temperature of charger or SSD is almost constant and always low, making the average temperature far lower than the actual CPU temp (e.g. in the picture, the actual temp is 49, but the software gives 30). So even when the temp of CPU is almost 80 degrees, the average temperature may be only 45 degrees, while when the temp is around 40, the average temperature is around 30. So if you want to modify the fan curve, only 2 points (40 & 45) are effective, which means you can't control the fan precisely. 
To solve the problem, I have 3 ideas:
1.Directly identify the temperature of the CPU if possible
2.Use the maximum of the temperatures instead of average
3.change the rage of the fan curve, add more points between 30-50 degree 
![屏幕截图 2024-12-10 100611](https://github.com/user-attachments/assets/c6551d62-01d7-4120-bd75-f8c7b81b450b)

**Comment by vladann93** [comment]
@zyy574 yes Your first suggestion is exactly what I did, the mac fan speed is at 45c and at 35c the fan is off. Like i said not ideal but a lot better than default. 
And yes I figured that ectools and Chrultrabook-Tools must be showing like an avg temp of something.
But none of that answers why that acer, and only that one, likes blasting its fans at full at all times. No warmup or restart or anything can change its behavior either, by default ectools does absolutley nothing on it.... and like i said i have all the drivers there.. everything else works, so really no clue whats up with that one... the other acer i have is great and quiet... but this ones horrible to use all because of the fan control...
Anyway thanks for your input

**Comment by death7654** [comment]
The reason why I decided to calculate the average is that there are chromebooks where choosing a sensor might be like you said an ssd, by taking the average all parts of the system can be taken care of. Some Chromebooks have 6 sensors or no sensors at all.

 I do wish we can read directly from the sensor, but not every device is made the same.

**Comment by death7654** [comment]
I will be using the "use highest temp" idea. An update will be pushed soon.
